Repository datalab-org/datalab, pull requests merged in 2023-11, with the labels that each got.

#490 Revamp installation docs with additional configuration/administration/deployment info
  INSTALL.md
  README.md
  mkdocs.yml
  pydatalab/docs/.pages
  pydatalab/docs/config.md
  pydatalab/pydatalab/config.py
  pydatalab/tasks.py
  webapp/package.json
Labels: documentation

#504 Rework e2e tests
  webapp/cypress/e2e/batchSampleFeature.cy.js
  webapp/cypress/e2e/editPage.cy.js
  webapp/cypress/e2e/sampleTablePage.cy.js
  webapp/cypress/support/commands.js
  webapp/cypress/support/e2e.js
Labels: testing

#497 CI build optimisations
  .docker/server_dockerfile
  .github/workflows/ci.yml
  docker-compose.yml
Labels: testing

#477 Labspec 1D Raman compatibility
  pydatalab/example_data/raman/labspec_raman_example.txt
  pydatalab/pydatalab/apps/raman/blocks.py
  pydatalab/tests/apps/test_raman.py
Labels: enhancement

#517 Add note about GitHub callback URL in docs
  pydatalab/docs/config.md
Labels: documentation
