Repository datalab-org/datalab, pull requests merged in 2024-09, with the labels that each got.

#874 Fix deployment config options for new VUE_APP settings
  .docker/app_dockerfile
  .docker/app_entrypoint.sh
  docker-compose.yml
Labels: bug, build

#873 Lockfile compatibility
  .gitignore
  INSTALL.md
  pydatalab/Pipfile
  pydatalab/Pipfile.lock
  pydatalab/pyproject.toml
  pydatalab/scripts/pipenv-resync.sh
  pydatalab/uv.lock
Labels: build, Python

#888 Fix some issues in the datatable
  webapp/src/components/CollectionSelect.vue
  webapp/src/components/DynamicDataTable.vue
Labels: webapp, usability
