Repository datalab-org/datalab, pull requests merged in 2024-10, with the labels that each got.

#904 Hotfix for new e2e test command
  webapp/cypress/support/commands.js
Labels: bug, testing

#905 Add support for XRD files that have indeterminate headers (e.g., diffrac.eva export)
  pydatalab/example_data/XRD/example_bmb.xye
  pydatalab/example_data/XRD/example_evadiffract.xy
  pydatalab/example_data/XRD/example_mac.xye
  pydatalab/example_data/XRD/example_mythen.dat
  pydatalab/example_data/XRD/example_mythen.xye
  pydatalab/pydatalab/apps/xrd/blocks.py
Labels: enhancement, datablock

#912 Re-enable lockfile only mode of dependabot
  .github/dependabot.yml
Labels: build, dependency_updates

#902 Add dropdown with actions buttons for selected items inside DataTable
  webapp/cypress/e2e/batchSampleFeature.cy.js
  webapp/cypress/e2e/equipment.cy.js
  webapp/cypress/e2e/sampleTablePage.cy.js
  webapp/cypress/support/commands.js
  webapp/src/components/DynamicDataTable.vue
  webapp/src/components/DynamicDataTableButtons.vue
Labels: webapp

#896 Refactor ID Validation Logic into Utility Function
  webapp/src/components/BatchCreateItemModal.vue
  webapp/src/components/CollectionSelect.vue
  webapp/src/components/CreateCollectionModal.vue
  webapp/src/components/CreateEquipmentModal.vue
  webapp/src/components/CreateItemModal.vue
  webapp/src/field_utils.js
Labels: webapp, refactoring

#917 Install datalab as editable inside docker build to make env passing simpler
  .docker/server_dockerfile
Labels: build

#919 Fix css issues in DynamicDataTable
  webapp/src/components/DynamicDataTable.vue
Labels: webapp

#925 Ensure that new collection `immutable_id` is returned upon creation
  pydatalab/src/pydatalab/routes/v0_1/collections.py
  pydatalab/tests/server/test_samples.py
Labels: bug, server

#930 Use git version inside app container build
  .docker/app_dockerfile
  .docker/app_entrypoint.sh
  .docker/server_dockerfile
  docker-compose.yml
Labels: build

#921 Set up custom primevue theme
  webapp/src/components/DynamicDataTable.vue
  webapp/src/main.js
  webapp/src/primevue-theme-preset.js
Labels: enhancement, webapp, visuals, javascript

#935 Fix bug where blocks would not be loaded automatically
  webapp/src/server_fetch_utils.js
  webapp/src/views/EditPage.vue
Labels: bug, priority/high

#937 Tweak for edit page to allow upload file modal to load correctly
  webapp/src/views/EditPage.vue
Labels: bug

#942 Hotfix for file-overwriting from uppy
  webapp/src/file_upload.js
Labels: bug, priority/high

#945 Add scheduled `uv lock -U` to replace dependabot
  .github/workflows/dependable-bot.yml
Labels: build

#959 Add suggested 'ready-for-review' workaround to checks not running from actions-created PRs
  .github/workflows/ci.yml
  .github/workflows/dependable-bot.yml
Labels: build, CI

#960 Add scheduled `yarn upgrade` job in CI
  .github/workflows/dependable-bot.yml
  .github/workflows/yarn-upgrade-bot.yml
Labels: build, dependency_updates, CI

#957 Remove `vue/cli` as dependency and add missing polyfills
  webapp/package.json
  webapp/vue.config.js
  webapp/yarn.lock
Labels: build, dependency_updates, javascript

#958 Split vue docker build into two stages
  .docker/app_dockerfile
Labels: build, webapp
