Repository datalab-org/datalab, pull requests merged in 2025-06, with the labels that each got.

#1213 Limit batch interface to 100 items in UI and 10,000 via API
  pydatalab/src/pydatalab/config.py
  pydatalab/src/pydatalab/routes/v0_1/items.py
  webapp/src/components/BatchCreateItemModal.vue
Labels: webapp, usability

#1233 Remove some vue-cli-plugins dev dependencies
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  webapp/package.json
  webapp/yarn.lock
Labels: build, dependency_updates, CI

#1244 Fix for molar mass validation with invalid formula of starting materials
  pydatalab/src/pydatalab/models/starting_materials.py
  pydatalab/tests/server/test_starting_materials.py
Labels: bug, API

#1227 Add relationships by `refcode` rather than `item_id` from the UI
  pydatalab/src/pydatalab/models/cells.py
  pydatalab/src/pydatalab/models/relationships.py
  pydatalab/src/pydatalab/models/traits.py
  pydatalab/src/pydatalab/models/utils.py
Labels: bug, API, server

#1242 Add exhaustive block API testing for all block types
  pydatalab/tests/server/test_blocks.py
Labels: testing, API

#1248 Fix some PyPI metadata
  pydatalab/pyproject.toml
Labels: build

#1252 Add note about inconsistencies in ways configs are specified
  pydatalab/docs/config.md
Labels: bug, documentation

#1255 Bump the uppy ecosystem to v4 and fix styling
  webapp/package.json
  webapp/src/file_upload.js
  webapp/yarn.lock
Labels: bug, webapp, visuals, usability
