Repository datalab-org/datalab, pull requests merged in 2025-08, with the labels that each got.

#1302 Set uv version in liccheck and dependable bot workflows
  .github/workflows/dependable-bot.yml
  .github/workflows/license-check.yml
Labels: CI

#1303 Update SMTP integration to recommend resend.com
  pydatalab/docs/config.md
Labels: documentation

#1212 Replace browser-native dialogs with custom datalab dialog service
  webapp/cypress/support/commands.js
  webapp/src/App.vue
  webapp/src/components/BatchCreateItemModal.vue
  webapp/src/components/CollectionSelect.vue
  webapp/src/components/CreateCollectionModal.vue
  webapp/src/components/CreateEquipmentModal.vue
  webapp/src/components/CreateItemModal.vue
  webapp/src/components/DialogContainer.vue
  webapp/src/components/DialogModal.vue
  webapp/src/components/DynamicDataTableButtons.vue
  webapp/src/components/EditAccountSettingsModal.vue
  webapp/src/components/FileList.vue
  webapp/src/components/ToggleableCreatorsFormGroup.vue
  webapp/src/components/UserTable.vue
  webapp/src/components/datablocks/DataBlockBase.vue
  webapp/src/file_upload.js
  webapp/src/main.js
  webapp/src/server_fetch_utils.js
  webapp/src/services/DialogService.js
  webapp/src/views/CollectionPage.vue
  webapp/src/views/EditPage.vue
Labels: webapp, visuals, usability
