Repository datalab-org/datalab, pull requests merged in 2025-03, with the labels that each got.

#1061 added ftir block and associated tests
  pydatalab/example_data/FTIR/2024-10-10_FeSO4_ref.asp
  pydatalab/src/pydatalab/apps/ftir/__init__.py
  pydatalab/src/pydatalab/blocks/__init__.py
  pydatalab/tests/apps/test_ftir_block.py
  webapp/src/resources.js
Labels: enhancement, datablock

#1054 Add overlay while deleting multiple items
  webapp/src/components/DynamicDataTableButtons.vue
Labels: webapp, usability

#1058 Attempt to bump uv to the 0.6.x series
  .docker/server_dockerfile
  .github/workflows/ci.yml
Labels: dependency_updates

#1067 Added support for rasx xrd files
  pydatalab/example_data/XRD/JO_KL_16_ZF_3_60deg_0.02step_12degpermin_001.rasx
  pydatalab/src/pydatalab/apps/xrd/blocks.py
  pydatalab/src/pydatalab/apps/xrd/utils.py
  pydatalab/tests/apps/test_xrd_block.py
Labels: enhancement, datablock
