Repository datalab-org/datalab, pull requests merged in 2025-07, with the labels that each got.

#1246 Add custom UI for new in situ UV-Vis block
  pydatalab/pyproject.toml
  pydatalab/src/pydatalab/apps/uvvis/__init__.py
  pydatalab/src/pydatalab/apps/uvvis/utils.py
  pydatalab/tests/apps/test_plugins.py
  pydatalab/tests/apps/test_uvvis.py
  pydatalab/uv.lock
  webapp/src/components/FolderSelect.vue
  webapp/src/components/datablocks/UVVisInsituBlock.vue
  webapp/src/resources.js
Labels: webapp, datablock

#1280 Fix item selection dropdown missing scrollbar in synthesis info
  webapp/cypress/e2e/batchSampleFeature.cy.js
  webapp/src/components/CompactConstituentTable.vue
  webapp/src/components/FormattedItemName.vue
  webapp/src/components/SynthesisInformation.vue
Labels: bug, webapp, usability

#1245 Improve and restructure README, plus other minor docs fixes
  CHANGELOG.md
  INSTALL.md
  README.md
  pydatalab/docs/INSTALL.md
  pydatalab/docs/blocks/index.md
  pydatalab/docs/config.md
  pydatalab/docs/deployment.md
  pydatalab/mkdocs.yml
Labels: documentation

#1294 Docs formatting improvements and fixes
  .readthedocs.yaml
  CHANGELOG.md
  pydatalab/docs/INSTALL.md
  pydatalab/docs/blocks/index.md
  pydatalab/docs/blocks/reference/apps/echem.md
  pydatalab/docs/blocks/reference/base.md
  pydatalab/docs/blocks/reference/common.md
  pydatalab/docs/config.md
  pydatalab/docs/deployment.md
  pydatalab/docs/schemas/collections.md
  pydatalab/mkdocs.yml
  pydatalab/pyproject.toml
  pydatalab/src/pydatalab/apps/ftir/__init__.py
  pydatalab/src/pydatalab/blocks/common.py
  pydatalab/uv.lock
Labels: documentation

#1259 Add test for sample with several example files attached to corresponding blocks
  pydatalab/example_data/media/grey_group_logo.jpeg
  pydatalab/tests/server/test_blocks.py
Labels: testing, API
